# Generated by Django 4.2.11 on 2025-06-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_online_app', '0002_products_image_alter_products_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
