# Generated by Django 4.2.11 on 2025-06-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_online_app', '0004_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
