# Generated by Django 5.2.3 on 2025-06-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_online_app', '0005_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
